### PR TITLE
update beacon message to cvc format

### PR DESCRIPTION
**Pull request by ajuvercr**
Accepts cvc beacon message format.

### CODE REVIEW

**Comment by ajuvercr** [comment]
hw_sim is not yet modified to supply this kind of messages.

**Comment by abeforgit** [comment]
is this still relevant? @ajuvercr

**Comment by ajuvercr** [comment]
I don't really remember this code at all, but it looks like an implementation of a beacon message format with simple strings instead of bytes.

If this is still the expected way of communication, yes, otherwise no but then a new implementation is required.

**Comment by abeforgit** [comment]
yeah I have no idea what format we want
though I do seem to vaguely remember that we decided we wanted strings for the ease of use

**Comment by ajuvercr** [comment]
Yeet this, new ronny format will be supported!

**Pull request closed without merging**
