### PR TITLE
feat: update dependencies

### PR DESCRIPTION
**Pull request by NuttyShrimp**
Swagger went BRRR

### CODE REVIEW

**Review by FKD13 — COMMENTED** [review]
Still compiles and runs :tada: 

Some remarks:
- We have lost our swagger endpoint grouping (everything is grouped under "default")
- do we want to update to java 21?
- this option seems to influence nothing? 
scr
- my ide seems happier with the bottom version :D 
scr

**Comment by NuttyShrimp** [comment]
I take a look at the swagger endpoint group but can't promise anything, the docs are pretty shit.

The `sourceCompatibility` definitely does something, it is used by [the java plugin](https://docs.gradle.org/current/userguide/java_plugin.html#toolchain_and_compatibility).
See what happens when I try to run the tests with compatibility set to 19 on a 17 sdk
image

We can upgrade to 21, but there are no new exciting features and 17 is backwards compatible with 21 so the peeps in their first year do not really need to download 17 (and I don't need to upgrade my SDK)

**Comment by NuttyShrimp** [comment]
- Fxed the swagger grouping
- Changed that build  thing in the gradle file
- Rebased onto development

**Comment by FKD13** [comment]
My migrations are currently failing with error: 

```
No database found to handle jdbc:postgresql://localhost:5432/telraam_dev
```

Probably linked to https://github.com/flyway/flyway/issues/3722

**Review by FKD13 — APPROVED** [review]
Glad the swagger still looks the same :tada:

**Pull request merged**
