### PR TITLE
add sonarqube to CI

### PR DESCRIPTION
**Pull request by mcbloch**
Blocked until the nginx of the sonarqube container is deployed

### CODE REVIEW

**Comment by abeforgit** [comment]
any update on this?

**Comment by mcbloch** [comment]
I'm waiting for this https://github.com/ZeusWPI/ansible-config/pull/125

**Comment by abeforgit** [comment]
okido

**Comment by abeforgit** [comment]
This should be ready to merge once we get a sonarqube instance going

Seems easy enough to add it to github actions as well

**Comment by abeforgit** [comment]
im gonna get rid of the travis config but back it up in the wiki

**Pull request merged**
