### PR TITLE
api endpoint now accepts query param 'seconds' so selection for detections of last n seconds can be done

### PR DESCRIPTION
**Pull request by Iwijn**
… of last n (max 600) seconds can be done

### CODE REVIEW

**Review by NuttyShrimp — CHANGES_REQUESTED** [review]
So, if a persons requests the detections of the last 5min the `handledDetections` is getting changed but the detections of 10min ago where not processed. I would opt for adding a bit of logic around it so it only changes when all the detections are requested and processed

**Comment by redfast00** [comment]
I'm not entirely following: what component of our counting system would use this endpoint?

**Comment by Iwijn** [comment]
this was for when monitoring directly used the api, so probably useless now.

**Comment by redfast00** [comment]
Thanks for the answer :)

**Pull request closed without merging**
